In [1]:
import numpy as np

a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [2]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [3]:
#Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [4]:
#Get shape (# of rows x # of columns)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [5]:
# Get array length (# of elements)
print(a.size)
print(b.size)

3
6


In [6]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


In [7]:
# Get size (bytes per element)
print(a.itemsize)
print(b.itemsize)

4
8


In [8]:
# Get total array size (total bytes)
print(a.size * a.itemsize)
print(a.nbytes)
print(b.size * b.itemsize)
print(b.nbytes)

12
12
48
48


In [9]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [14]:
# Get a specific element: [row, column]
print(c[1,5])
print(c[1,-2])

13
13


In [21]:
#Get a specific row
print(c[0,:])
print(c[0,:].shape)

[1 2 3 4 5 6 7]
(7,)


In [22]:
#Get a specific column
print(c[:, 2])
print(c[:, 2].shape)

[ 3 10]
(2,)


In [27]:
# Fancy access (startindex:endindex:stepsize) --> endindex won't be included
print(c[0, 1:6:2])
print(c[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [29]:
c[1,5]=20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [31]:
c[:, 2] = 0
print(c)
c[:, 2] = [-1,-2]
print(c)

[[ 1  2  0  4  5  6  7]
 [ 8  9  0 11 12 20 14]]
[[ 1  2 -1  4  5  6  7]
 [ 8  9 -2 11 12 20 14]]


In [41]:
# 3D example (1,2,3,4 on front closer face; 5,6,7,8 behind it) 
b = np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] ])
print(b)
print(b[0,1,1]) # [depth, row, column]
print(b[:,0,0]) # [depth, row, column]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[1 5]


In [44]:
# Replace 3D array
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [55]:
# All 0s 
print(np.zeros(5, dtype='int16'))
print(np.zeros((2,3)))

[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
# All 1s 
print(np.ones(5))
print(np.ones((2,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [65]:
# Fill with any other number
print(np.full((2,4),99))
print(np.full_like(c,6))
print(np.full(c.shape,8))

[[99 99 99 99]
 [99 99 99 99]]
[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [112]:
# Diagonal with 1s
print(np.eye(3,2))
print(np.eye(3))
print(np.identity(3))

[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [108]:
# Random decimal numbers between 0.0-1.0
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.20561584 0.18609491]
 [0.70867802 0.58688303]
 [0.26772938 0.66282422]
 [0.14723234 0.37631878]]
[0.41605455 0.46310036 0.65857571]


In [109]:
# Random positive/negative integer numbers in range of arguments: [start,end)
print(np.random.randint(4,8, size=(4,2)))
print(np.random.randint(-3,-1, size=(2,2)))

[[7 6]
 [4 5]
 [7 7]
 [7 7]]
[[-2 -3]
 [-3 -3]]


In [129]:
# Repeat an array in different axes
arr_1 = np.array([1,2,3]) # This is 1-D array (rank-1), so only repeated in 1 axis
print(arr_1)
r1 = np.repeat(arr_1, 3)
print(r1)

print("\n")

arr_2 = np.array([[1,2,3]]) # This is 2-D array (rank-2), can be repeated in 2 axis
print(arr_2)
r2 = np.repeat(arr_2, 3, axis=0)
print(r2)
r2 = np.repeat(arr_2, 3, axis=1)
print(r2)

[1 2 3]
[1 1 1 2 2 2 3 3 3]


[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [139]:
# Simple practice
test = np.ones((5,5))
test[1:-1, 1:-1] = 0
test[2,2] = 9
test

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [145]:
# Naive way of copying arrays
old = np.array([1,2,3])
print(old)
new = old
print(new)
new[0] = 100
print(new)
print(old)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


In [146]:
# Robust way of copying arrays
old = np.array([1,2,3])
print(old)
new = old.copy()
print(new)
new[0] = 100
print(new)
print(old)

[1 2 3]
[1 2 3]
[100   2   3]
[1 2 3]


In [166]:
# Basic math operations
a = np.array([1,2,3,4],dtype='int32')
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a//2)
print(a%2)
a+=9
print(a)
b = np.array([1,-1,1,-1],dtype='int32')
print(a**2)
print(np.sin(a))

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[1 0 1 0]
[10 11 12 13]
[100 121 144 169]
[-0.54402111 -0.99999021 -0.53657292  0.42016704]


In [186]:
# Linear algebra operations
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

print(np.matmul(a,b))
print(a @ b)

print("\n")

c = np.eye(3)
print(c)
print(np.linalg.det(c))
print(np.linalg.trace(c))
print(np.linalg.inv(c))
print(c @ b)

print("\n")

m = np.array([1, 2, 3])
n = np.array([4, 5, 6])
print(np.dot(m, n))
print(np.dot(n, m))
print(m @ n)
print(n @ m)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0
3.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


32
32
32
32


In [199]:
# Statistical operations
stats = np.array([[1, 2, 3],[4, 5, 6]])
print(stats)
print(np.mean(stats))
print(np.min(stats))
print(np.min(stats,axis=0)) #Column-wise: It looks down each column and picks the smallest number.
print(np.min(stats,axis=1)) #Row-wise: It looks across each row and picks the smallest number.
print(np.max(stats))
print(np.std(stats))
print(np.sum(stats))
print(np.sum(stats,axis=0))
print(np.sum(stats,axis=1))

[[1 2 3]
 [4 5 6]]
3.5
1
[1 2 3]
[1 4]
6
1.707825127659933
21
[5 7 9]
[ 6 15]


In [200]:
# Reorganizing arrays

