In [3]:
import numpy as np

a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
#Get shape (# of rows x # of columns)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# Get array length (# of elements)
print(a.size)
print(b.size)

3
6


In [8]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


In [9]:
# Get size (bytes per element)
print(a.itemsize)
print(b.itemsize)

4
8


In [10]:
# Get total array size (total bytes)
print(a.size * a.itemsize)
print(a.nbytes)
print(b.size * b.itemsize)
print(b.nbytes)

12
12
48
48


In [11]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [12]:
# Get a specific element: [row, column]
print(c[1,5])
print(c[1,-2])

13
13


In [13]:
#Get a specific row
print(c[0,:])
print(c[0,:].shape)

[1 2 3 4 5 6 7]
(7,)


In [14]:
#Get a specific column
print(c[:, 2])
print(c[:, 2].shape)

[ 3 10]
(2,)


In [15]:
# Fancy access (startindex:endindex:stepsize) --> endindex won't be included
print(c[0, 1:6:2])
print(c[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [16]:
c[1,5]=20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
c[:, 2] = 0
print(c)
c[:, 2] = [-1,-2]
print(c)

[[ 1  2  0  4  5  6  7]
 [ 8  9  0 11 12 20 14]]
[[ 1  2 -1  4  5  6  7]
 [ 8  9 -2 11 12 20 14]]


In [18]:
# 3D example (1,2,3,4 on front closer face; 5,6,7,8 behind it) 
b = np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] ])
print(b)
print(b[0,1,1]) # [depth, row, column]
print(b[:,0,0]) # [depth, row, column]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[1 5]


In [19]:
# Replace 3D array
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [20]:
# All 0s 
print(np.zeros(5, dtype='int16'))
print(np.zeros((2,3)))

[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# All 1s 
print(np.ones(5))
print(np.ones((2,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# Fill with any other number
print(np.full((2,4),99))
print(np.full_like(c,6))
print(np.full(c.shape,8))

[[99 99 99 99]
 [99 99 99 99]]
[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [23]:
# Diagonal with 1s
print(np.eye(3,2))
print(np.eye(3))
print(np.identity(3))

[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Random decimal numbers between 0.0-1.0
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.01520958 0.8453391 ]
 [0.31500909 0.18479921]
 [0.87918124 0.84798559]
 [0.72531194 0.19674838]]
[0.33580845 0.76099633 0.3799167 ]


In [25]:
# Random positive/negative integer numbers in range of arguments: [start,end)
print(np.random.randint(4,8, size=(4,2)))
print(np.random.randint(-3,-1, size=(2,2)))

[[4 4]
 [6 4]
 [4 4]
 [7 4]]
[[-3 -2]
 [-2 -3]]


In [26]:
# Repeat an array in different axes
arr_1 = np.array([1,2,3]) # This is 1-D array (rank-1), so only repeated in 1 axis
print(arr_1)
r1 = np.repeat(arr_1, 3)
print(r1)

print("\n")

arr_2 = np.array([[1,2,3]]) # This is 2-D array (rank-2), can be repeated in 2 axis
print(arr_2)
r2 = np.repeat(arr_2, 3, axis=0)
print(r2)
r2 = np.repeat(arr_2, 3, axis=1)
print(r2)

[1 2 3]
[1 1 1 2 2 2 3 3 3]


[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [27]:
# Simple practice
test = np.ones((5,5))
test[1:-1, 1:-1] = 0
test[2,2] = 9
test

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Naive way of copying arrays
old = np.array([1,2,3])
print(old)
new = old
print(new)
new[0] = 100
print(new)
print(old)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


In [29]:
# Robust way of copying arrays
old = np.array([1,2,3])
print(old)
new = old.copy()
print(new)
new[0] = 100
print(new)
print(old)

[1 2 3]
[1 2 3]
[100   2   3]
[1 2 3]


In [30]:
# Basic math operations
a = np.array([1,2,3,4],dtype='int32')
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a//2)
print(a%2)
a+=9
print(a)
b = np.array([1,-1,1,-1],dtype='int32')
print(a**2)
print(np.sin(a))

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[1 0 1 0]
[10 11 12 13]
[100 121 144 169]
[-0.54402111 -0.99999021 -0.53657292  0.42016704]


In [31]:
# Linear algebra operations
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

print(np.matmul(a,b))
print(a @ b)

print("\n")

c = np.eye(3)
print(c)
print(np.linalg.det(c))
print(np.linalg.trace(c))
print(np.linalg.inv(c))
print(c @ b)

print("\n")

m = np.array([1, 2, 3])
n = np.array([4, 5, 6])
print(np.dot(m, n))
print(np.dot(n, m))
print(m @ n)
print(n @ m)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0
3.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


32
32
32
32


In [32]:
# Statistical operations
stats = np.array([[1, 2, 3],[4, 5, 6]])
print(stats)
print(np.mean(stats))
print(np.min(stats))
print(np.min(stats,axis=0)) #Column-wise: It looks down each column and picks the smallest number.
print(np.min(stats,axis=1)) #Row-wise: It looks across each row and picks the smallest number.
print(np.max(stats))
print(np.std(stats))
print(np.sum(stats))
print(np.sum(stats,axis=0))
print(np.sum(stats,axis=1))

[[1 2 3]
 [4 5 6]]
3.5
1
[1 2 3]
[1 4]
6
1.707825127659933
21
[5 7 9]
[ 6 15]


In [33]:
# Reorganizing arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

print("\n")

after_2d = before.reshape((4,2))
print(after_2d)
print(after_2d.shape)

print("\n")

after_3d = before.reshape((2,2,2))
print(after_3d)
print(after_3d.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [34]:
# Vertical & horizontal stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack((v1,v2,v1)))
print(np.hstack((v1,v2,v1)))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]
[1 2 3 4 5 6 7 8 1 2 3 4]


In [35]:
# Misc
a = np.array([1,2,3,4])
print(a)
b = a.astype('float64')
print(b)

[1 2 3 4]
[1. 2. 3. 4.]


In [36]:
# Advanced indexing and boolean masking
a = np.random.rand(5,2)
print(a)
print(a < 0.5)
print(a[a < 0.5])
print(a[(a > 0.2) & (a < 0.6)])

print("\n")

print(np.any(a < 0.2, axis=0)) # Checks if any of the elements per column is less than 0.2
print(np.any(a < 0.2, axis=1)) # Checks if any of the elements per row is less than 0.2
print(np.all(a > 0.3, axis=0)) # Checks if all of the elements per column is greater than 0.3
print(np.all(a > 0.3, axis=1)) # Checks if all of the elements per row is greater than 0.3



[[0.07374553 0.44005717]
 [0.86044518 0.55778868]
 [0.32120252 0.32823776]
 [0.70913489 0.65958241]
 [0.63013502 0.76777684]]
[[ True  True]
 [False False]
 [ True  True]
 [False False]
 [False False]]
[0.07374553 0.44005717 0.32120252 0.32823776]
[0.44005717 0.55778868 0.32120252 0.32823776]


[ True False]
[ True False False False False]
[False  True]
[False  True  True  True  True]


In [37]:
# Intermediate practice example
a = np.array([ [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30] ])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [38]:
print(a[2:4,0:2])
print(a[ [0,1,2,3], [1,2,3,4,] ])
print(a[ [0,4,5], 3:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
