In [21]:
import numpy as np

a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [22]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [23]:
#Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [31]:
#Get shape (# of rows x # of columns)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [27]:
# Get array length (# of elements)
print(a.size)
print(b.size)

3
6


In [28]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


In [29]:
# Get size (bytes per element)
print(a.itemsize)
print(b.itemsize)

4
8


In [32]:
# Get total array size (total bytes)
print(a.size * a.itemsize)
print(a.nbytes)
print(b.size * b.itemsize)
print(b.nbytes)

12
12
48
48


In [34]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
